# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aseem's blog
email: aseempathak21@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey this is Aseem!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://noyce.github.io" # the base hostname & protocol for your site
#twitter_username: 
github_username:  noyce
reddit_username: noyce21
# Build settings
markdown: kramdown
